export const ADMIN_ROUTE = "/admin"
export const LOGIN_ROUTE = "/auth"
export const REGISTRATION_ROUTER = "/registration"
export const REQUEST_ROUTER = "/request"
export const MAKE_REQUEST_ROUTER = "/make_request"